### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by iamkarlson**
Pls review pr.

### CODE REVIEW

**Comment by BladeMight** [comment]
Okay, I'll let you know as soon as I finish reviewing.

**Comment by BladeMight** [comment]
What? You are using third party NLOG? I'm not fan of third parties, so I don't like that Log type.... I'll create my own log system, that what I always do - Create my own.
What about Mahou Size? It has grown to 500+ kb and uses third party DLL, sorry I can't allow that, I like to be simple one exe file without any third-party files.
I always create own class, functions, or something I don't like third-party files, that is my programming Philosophy.
Thanks but *no*, that can't be merged due to **my programming Philosophy**.

**Comment by BladeMight** [comment]
@iamkarlson I added my **own** logging system which takes just ~13 kb of space, take a look [v1.4.3.2](https://github.com/BladeMight/Mahou/releases/tag/v1.4.3.2)

**Comment by iamkarlson** [comment]
facepalm

**Pull request closed without merging**
